[config]
schemaVersion = "0.0.1"

[package]
namespace = "Sparroh"
name = "UltimateMovement"
description = "*WARNING* (This is a cheat mod) Enables ability to Fire and Aim while Sprinting and Sliding for fluid gameplay. Also enables Aim while Reloading and Wallrunning."
websiteUrl = "https://github.com/Little-Sparroh/FireWhileSprinting"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/UltimateMovement.dll"
target = "BepInEx/plugins/UltimateMovement.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]


